=== AndreiKovalevv/XML_rasspisanie/schemaRasp.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="schedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="title"/>
        <xs:element name="day" maxOccurs="12">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name-day"/>
              <xs:element name="lesson" maxOccurs="4" minOccurs="0">
                <xs:complexType>
                  <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element type="xs:string" name="time"/>
                    <xs:element type="xs:string" name="name-lesson"/>
                    <xs:element type="xs:string" name="office"/>
                    <xs:element name="parity-week">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element type="xs:string" name="time" minOccurs="0"/>
                          <xs:element type="xs:string" name="name-lesson"/>
                          <xs:element type="xs:string" name="office" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:choice>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AndreiKovalevv/XML_rasspisanie/Рассписание ИФСТ-31.xml
<schedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:noNamespaceSchemaLocation="schemaRasp.xsd">
  <title>Расписание занятий группы ИФСТ-31</title>
  <day>
    <name-day>Понедельник</name-day>
      <lesson>
        <time>8:30 - 10:00</time>
        <name-lesson>Элективные курсы по физической культуре</name-lesson>
        <office>Спортивный зал </office>
     </lesson>
    <lesson>
      <time>10:10 - 11:40</time>
      <name-lesson>Иностранный язык для проф.общения</name-lesson>
      <office>433 кабинет</office>
    </lesson>
    <lesson>
      <time>12:10 - 13:40</time>
      <name-lesson>Современные технологии интернетпрограммирования</name-lesson>
      <office> ВЦ </office>
    </lesson>
    </day>
  <day>
    <name-day>Вторник</name-day>
     <lesson>
      <time>10:10 - 11:40</time>
      <name-lesson>М/м технологии</name-lesson>
      <office>ВЦ </office>
    </lesson>
    <lesson>
      <time>12:10 - 13:40</time>
      <name-lesson>Моделирование процессов и систем</name-lesson>
      <office> 102 кабинет </office>
    </lesson>
  </day>
  <day>
    <name-day>Среда</name-day>
    <lesson>
      <time>8:30-10:00</time>
      <name-lesson>Технологии создания web-ресурсов</name-lesson>
      <office>102 кабинет </office>
    </lesson>
    <lesson>
      <parity-week> Нечётная неделя
      <time>10:10 - 11:40</time>
      <name-lesson>Технологии создания web-ресурсов</name-lesson>
      <office> 102 кабинет </office>
      </parity-week>
      <parity-week>Чётная неделя неделя
        <time>10:10 - 11:40</time>
        <name-lesson>Арх-ра инф.систем</name-lesson>
        <office> 102 кабинет </office>
      </parity-week>
    </lesson>
  </day>
  <day>
    <name-day>Четверг</name-day>
    <lesson>
      <parity-week>
        Нечётная неделя
        <time>10:10 - 11:40</time>
        <name-lesson>ФНиТ</name-lesson>
        <office>420 </office>
      </parity-week>
      <parity-week>
        Чётная неделя
        <time>10:10 - 11:40</time>
        <name-lesson>Архитектура информационных систем</name-lesson>
        <office> ВЦ </office>
      </parity-week>
    </lesson>
    <lesson>
      <time>12:10 - 13:40</time>
      <name-lesson>Архитектура информационных систем</name-lesson>
      <office> ВЦ </office>
    </lesson>
  </day>
  <day>
    <name-day>Пятница</name-day>
    <lesson>
      <time>8:30 - 10:00</time>
      <name-lesson>
        Современные технологии управения базами
        данных
      </name-lesson>
      <office>102 кабинет </office>
    </lesson>  
    <lesson>
        <parity-week>
          Нечётная неделя
          <time>10:10 - 11:40</time>
          <name-lesson>Элективные курсы по физической культуре</name-lesson>
          <office>Спортивный зал </office>
        </parity-week>
        <parity-week>
          Чётная неделя
          <time>10:10 - 11:40</time>
          <name-lesson>Совр.технологии упр-я базами данных</name-lesson>
          <office> 102 кабинет </office>
        </parity-week>
      </lesson>
  </day>
  <day>
    <name-day>Суббота</name-day>
    <lesson>
      <time>8:30 - 10:00</time>
      <parity-week>
        Нечётная неделя
        <name-lesson>
          Философия науки и техники
        </name-lesson>
      <office>Дистанционно</office>
      </parity-week>
      <parity-week>
        Чётная неделя
        <name-lesson>
         Занятий нет
        </name-lesson>
      </parity-week>
    </lesson>
    <lesson>
      <time>12:10 - 13:40</time>
      <name-lesson>
        Современные технологии ООП
      </name-lesson>
      <office>ВЦ</office>
    </lesson>
    <lesson>
      <parity-week>
        Чётная неделя
        <time>13:50 - 15:20</time>
      <name-lesson>        
        Современные технологии ООП
      </name-lesson>
      <office>ВЦ</office>
        </parity-week>
      <parity-week>
        Нечётная неделя
        <name-lesson>
          Занятий нет
        </name-lesson>
        </parity-week>
    </lesson>
    </day>
  </schedule>
